# Generated by Django 5.2.10 on 2026-06-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invite_code_sos_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_sharing_live_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
