# Generated by Django 5.2.10 on 2026-07-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sosalert_is_resolved_sosalert_resolved_at_and_more'),
        ('tracking', '0002_travelsession_destination_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sosalert",
            name="travel_session",
        ),

        migrations.AddField(
            model_name="sosalert",
            name="travel_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sos_alerts",
                to="tracking.travelsession",
            ),
        ),
    ]