# Generated by Django 5.2.8 on 2026-07-04 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sosalert_travel_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sos_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
