# Generated by Django 5.2.8 on 2026-06-29 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Session',
                'verbose_name_plural': 'Travel Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.travelsession')),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Location Histories',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='travelsession',
            index=models.Index(fields=['student', 'status'], name='tracking_tr_student_b4ffc3_idx'),
        ),
        migrations.AddIndex(
            model_name='travelsession',
            index=models.Index(fields=['status', 'last_update_at'], name='tracking_tr_status_c2005e_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['session', 'recorded_at'], name='tracking_lo_session_998569_idx'),
        ),
    ]
