# Generated by Django 5.2.8 on 2026-07-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelsession',
            name='destination_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelsession',
            name='duration',
            field=models.DurationField(blank=True, help_text='Journey duration', null=True),
        ),
        migrations.AddField(
            model_name='travelsession',
            name='start_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelsession',
            name='total_distance',
            field=models.FloatField(blank=True, help_text='Total distance in kilometers', null=True),
        ),
    ]
